:source-highlighter: highlight.js
:highlightjs-theme: atom-one-dark-reasonable
[,javascript]

= Object literal (物件實字)

* 用大括號來建立物件的語法
* 屬性用名值對(name-value pairs)表示

[source, javascript]

----
const person = {
    firstName: "John",
    lastName: "Doe",
    age: 30,
    isEmployed: true
};

----

* ES6後，物件的擴展（object literal extension）
* 物件屬性簡寫
* 變數名稱和屬性名稱一樣
* 物件的屬性名稱為變數的名稱，物件的屬性值為變數的值

[source, javascript]
----
let text = '我是誰';
let msg2 = { // 縮寫前
  text: text
};
let msg2 = { text }; // 縮寫後 
----
* 物件函式的語法簡寫
* 省略了冒號 : 和 function 關鍵字
* 這樣簡寫的方法，預設的屬性名稱會是字串的型態，本的簡寫 fn( ){...} 等同於 'fn'( ){...} 

[source, javascript]
----
// ES5
let obj1 = {
  fn: function() {
    return 'ES5';
  }
};
// ES6
let obj3 = {
  fn() {
    return 'ES6';
  }
};
----
* 具運算性的屬性名稱
* 使用 中括號[ ] 將表達式作為屬性名稱

[source, javascript]
----
let obj = {
  ["na"+"me"]: 'kent'
}
console.log(obj.name); // kent
----

== Optional Chaining

* 可選串連運算子
* 在「要確認的屬性或函式」後方「加上或換上」「?.」
* 避開TypeError Exception
* 判斷當前（?. 左側）這個屬性或函式是否為 Nullish 值：也就 undefined 或 null，有的話會往右繼續執行，否則就停止執行，並回傳undefined

[source, javascript]

----
const releasedYear = phone?.year;
//先確認 phone 屬性再取得 year 屬性值回傳
----

== JavaScript Object vs JSON

* JSON就是一組字串(純文字)
* JavaScript Object在使用{ }建立物件時，屬性名稱是可以有引號也可以沒有的，但在JSON格式中，屬性名稱一定要有引號
* 物件中的值為function，是無法透過JSON傳遞的

* 將物件轉成JSON格式 JSON.stringify();
* 將JSON格式轉成物件 JSON.parse()

== HTTP
.主要特點：
* 無狀態(stateless)：每個請求與其之前或之後的請求無關
* 可擴展(scalable)：通過標頭和方法可以擴展功能
* 安全性：HTTPS（HTTP Secure）提供了加密和身份驗證

** HTTP status Code不屬於狀態，是請求完成後的結果

== HTTP Headers/Payload

發請求和接收回應的重要組成部分

用一個信封比喻

* HTTP Headers=> 地址、寄件人、收件人...

* Payload => 信件內容

---


=== HTTP Headers：

客戶端和服務器之間互動所附加的的訊息(如瀏覽器類型、 傳遞的資料類型etc..)


自定義的header訊息用『x-』開頭，大多數已經廢除。

* 例子: 

 x-content-type-options:　nosniff //響應式網頁相關 
 


HTTP Headr分類：

==== 1.Request Headers

客戶端發出請求時夾帶的訊息，如要訪問的伺服器名稱、可接受的編碼格式等


常見的Request headers訊息：

  * Host: 訪問的伺服器主機名稱
  
   Host: www.w3schools.com

  * User-Agent：客戶端應用程序的資訊
    
   User-Agent：　Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36

  * Accept-Encoding： 客戶端編碼格式

  　Accept-Encoding: gzip, deflate, br

  *  Request methods:HTTP 請求方式
  　Request methods:HTTP: GET /index.html


==== 2.Response Headers

伺服器回應的訊息。
  
常見的Response headers訊息：
  
  * Server: 伺服器端的server類型
  
   Server :ECS (hhp/9ABD)
  
  * Date: 回傳日期

   Date: Wed, 31 Jul 2024 02:12:13 GMT

  * Status Code: 回傳執行結果
   Status Code:200 OK



==== 3.Representation header

表示回傳內容的格式，放在response Header裡面

* Content-Type: 回傳資源的格式
 
 Content-Type: text/html

* Content-Encoding: 編碼

 Content-Encoding: gzip

* Content-Language： 語言

 Content-Language： en



==== Payload：

request和respon包含的數據內容。

==== Payload Vs form

[width=85%, cols="2,4,3"]
[options="header"]
[%autowidth]
|===
| |Payload |form
|資料格式 |支援多種格式 如: json、xml、URL編碼格式... |URL編碼格式、
多部分編碼格式
|Context-type 
| application/json .1+| application/x-www-form-urlencoded
|資料格式|{
  "name": "John Doe",
  "age": 30
}| name=John+Doe&age=30
|===

  https://blog.csdn.net/qq_43842093/article/details/125883101

== Request Method
.GET
* 查詢
* 會回傳結果，帶參數的查詢會加在URL上面
[帶參數GET方法URL]

---
https://book.tpml.edu.tw/search?searchInput=javascript&searchField=FullText

---

.HEAD
* 查詢對象的資訊
* 不會回傳資料

.POST
* 增、改
* 較常用在新增資料
* 修改的項目會包在body裡面

.PUT
* 增、改	
* 常用在修改資料
* 整筆覆蓋
* 若修改對象不存在 => 新增一筆新的
* 修改的項目會包在body裡面

.PATCH
* 修改資料
* 只修改異動的部分部分

.DELETE
* 刪除資料

.CONNECT
* 建立連線
EX.代理伺服器連線

.OPTIONS
* 查詢對方可用支援那些HTTP 方法

.TRACE		
* 偵測HTTP請求其間是否有變化，中間路由若有錯誤可用此方法
* HTML表單內不適用

== 什麼是跨域資源共享(Cross-Origin Resource Sharing) ?
瀏覽器的同源政策(Same-Origin-Policy)

同源必須符合三項條件:

. 同通訊埠(port)

. 同通訊協定(protocol)

. 同網域(domain)

假如現在後端設定 Access-Control-Allow-Origin 為: https://eip.systex.com

[source, javascript]
----
http://eip.systex.com/  // 不同 protocal, 非同源

http://eip.systex.com:5000/ // 不同 port, 非同源

https://eip.system.com/  // 不同 domain, 非同源

http://eip.systex.com/Login.aspx // 同源
----

=== 流程: 

==== 一、簡單請求(Simple Requests)

當 Request Method 為：GET、POST、HEAD 
瀏覽器就會發送 Simple Request 給 Server, 並在 header 上帶上 Origin

==== Request Headers
----
GET / HTTP/1.1
Host: eip.systex.com
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,/;q=0.8
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-TW,en;q=0.9
Origin: http://example.com/
----

==== Response Headers
----
HTTP/1.1 200 OK
Content-Type: text/html; charset=UTF-8
Content-Length: 1234
Access-Control-Allow-Origin: http://example.com/
----


==== 二、預檢請求(Preflighted requests)

只要不符合簡單請求，瀏覽器會先送一次 HTTP Request, 一旦預檢請求成功完成，真正的請求才會被送出, 但預檢請求也不是每次都會觸發，可以設定 Access-Control-Max-Age 預檢請求回應快取的秒數，也就是說在這秒數內可以向 Simple Request 一樣, 直接發送請求。


== 什麼是跨站請求偽造(Cross Site Reuqest Forgery)？
在使用者已經驗證身份的網站中, 執行惡意的偽造操作。

Step1: 使用者成功登入 A 銀行網站的帳戶，並且代表使用者身份的 cookie 在 local 保存下來，所以下次再來訪問 A 銀行網站時，就不用重新登入

Step2: 因為使用者沒有登出 A 銀行網站的帳戶，在瀏覽 B 惡意網站時，B 網站有個被設為透明的圖片，因為是透明的，所以使用者在畫面上看不到，然而該圖片包含一段惡意程式碼，連結如下。

----

<img
  src="http://a-bank.com/transfer.do?acct=BadGuy&amount=100000 HTTP/1.1"
  width="0"
  height="0"
/>

----

Step3: 雖然使用者看不到此圖片， 但是，瀏覽器仍會向 http://a-bank.com/ 提交請求，同時此請求是帶有使用者的 cookie，所以 A 銀行可以辨識使用者身份，這個惡意攻擊會執行成功。